# Generated by Django 3.1.4 on 2021-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.jpg', null=True, upload_to='profile/'),
        ),
    ]
